Article/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('articleApp.urls','articleApp'),namespace='articleApp')),
       

 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleApp/urls.py
from django.urls import path
from .views import SignUpView
from django.contrib.auth.views import LoginView,LogoutView
from . import views

app_name = 'articleApp'
urlpatterns = [
    path('',views.articleview,name='articleList'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('article/',views.addarticle,name='article'),
    path('draft/',views.draftview,name='draft'),
    path('delete/<int:id>',views.delete_article,name='delete'),
    path('update/<int:id>',views.update_article,name='update'),
    path('articleList/',views.articleview,name='articleList'),
    path('myarticle/',views.my_article,name='myarticle'),  

]

articleApp/models.py
from django.db import models
from django.contrib.auth.models import User
 
class Tag(models.Model):
    tags=models.CharField(max_length=250)
    def __str__(self):
        return self.tags

class Article(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user',null=True)
    image = models.ImageField(blank=True, upload_to='article_image', null=True)
    title=models.CharField(max_length=100)
    content=models.TextField(max_length=250)
    created_at = models.DateTimeField(null=True,auto_now_add=True)
    tag=models.ManyToManyField(Tag,related_name='tag')
    draft= models.BooleanField(default=False)
   

    def __str__(self):
        return self.title
  



    

articleApp/forms.py
from tkinter import Widget
from turtle import title
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Article

class SignUpForm(UserCreationForm):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    email=forms.EmailField(max_length=250)
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password1','password2',]

class ArticleForm(forms.ModelForm):
    articletag=forms.CharField(max_length=500,widget=forms.Textarea(attrs={'cols': 40, 'rows': 2}))
    class Meta:
        model=Article
        fields=['title','content','image','draft','articletag']
       
class ArticleUpdateForm(forms.ModelForm):
    articletag=forms.CharField(max_length=500,widget=forms.Textarea(attrs={'cols': 40, 'rows': 2}))
    class Meta:
        model=Article
        fields=['title','content','image','draft','articletag',]
    
       

articleApp/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView
from .models import Article,Tag
from .forms import ArticleUpdateForm, SignUpForm,ArticleForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.db.models import Count

class SignUpView(CreateView):
    form_class=SignUpForm
    success_url=reverse_lazy("articleApp:login")
    template_name="signup.html"

def addarticle(request):
    if request.POST:    
        form=ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            userform=form.save(commit=False)
            articletag = form.cleaned_data.get('articletag')
            alltag=articletag.split(',')
            alltags=Tag.objects.values_list('tags',flat=True)
            newtags=list(set(alltag).difference(list(alltags)))
            listtag=[]
            Tag.objects.bulk_create([Tag(tags=tag) for tag in newtags])
            for tag in alltag:
                listtag+=Tag.objects.filter(tags=tag)
            userform.user=request.user
            userform.save()
            userform.tag.add(*listtag)
            form.save_m2m()
            return HttpResponseRedirect(reverse('articleApp:draft'))
        else:
            print('form is invalid')

    form=ArticleForm()
    return render(request,'article.html',{'form':form})
    

def articleview(request):
    article = Article.objects.filter(draft=False)
    tags=Article.objects.values('tag__tags').annotate(the_count=Count('tag')).filter(draft=False).order_by('-the_count')[:5]
    list_article=  [art.id for art in article]
    mytag=Article.objects.filter(draft=False,id__in=list_article).values('id',"tag__tags")
    return render(request,'articleList.html',{'articleList':article,'tags':tags,'mytag':mytag})

def my_article(request):
    myarticle = Article.objects.filter(draft=False,user=request.user) 
    list_article=  [art.id for art in myarticle]
    mytag=Article.objects.filter(draft=False,user=request.user,id__in=list_article).values('id',"tag__tags")
    return render(request,'myarticle.html',{'myarticle':myarticle,'mytag':mytag})
    
def draftview(request):
    draft = Article.objects.filter(draft=True,user=request.user)
    list_article=  [art.id for art in draft]
    mytag=Article.objects.filter(draft=True,user=request.user,id__in=list_article).values('id',"tag__tags")
    return render(request,'draftList.html',{'draftList':draft,'mytag':mytag})

def delete_article(request,id):
    Article.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('articleApp:draft'))

def update_article(request,id):
    instance=get_object_or_404(Article,pk=id)
    all_tags =instance.tag.all()
    all_tag=','.join(str(e)for e in all_tags)    
    if request.POST:
        form=ArticleUpdateForm(request.POST,request.FILES,instance=instance) 
        if form.is_valid():
            userform=form.save(commit=False)
            articletag = form.cleaned_data.get('articletag')
            alltag=articletag.split(',')
            alltags=Tag.objects.values_list('tags',flat=True)
            newtags=list(set(alltag).difference(list(alltags)))
            delete_tag=list(set(all_tag.split(',')).difference(list(alltag)))
            listtag=[]
            delete_tags=[]
            Tag.objects.bulk_create([Tag(tags=tag) for tag in newtags])
            for tag in alltag:
                listtag+=Tag.objects.filter(tags=tag)
            for tag in delete_tag:
                delete_tags+=Tag.objects.filter(tags=tag)
            form.save()
            userform.tag.add(*listtag)
            userform.tag.remove(*delete_tags)
            return HttpResponseRedirect(reverse('articleApp:draft'))
        else:
            print("form is invalid")
           
    form=ArticleUpdateForm(instance=instance)
    form2 = ArticleUpdateForm(initial={'articletag':all_tag})
    return render(request,'updatearticle.html',{'form':form,'form2':form2})

articleApp/templates/article.html
{% extends 'base.html' %}

{% block content %}
  <div class="centerform">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <div class="mb-3">
        <label  class="form-label">Title</label>
        <p>{{form.title}}</p>
      </div>
      <div class="mb-3">
        <label  class="form-label">Content</label>
        <p>{{form.content}}</p>
      </div>
      <div class="mb-3">
        <label  class="form-label">Image</label>
       <p> {{form.image}}</p>
      </div>
      <div class="mb-3">
        <label class="form-label">Tags</label>
        <p>{{form.articletag}}</p>
      </div>
      <div class="mb-3">
        <p>{{form.draft}} Save As Draft</p>
      </div>
      <button type="submit" class="btn btn-success">Save</button>
      <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
  </form>
  
  </div>

  {% endblock content %}

articleApp/templates/articleList.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="container-md">
  <div class="row">
    <div class="col-md-8 center">
      {% for Article in articleList %}
        <h2 class="text-primary">{{Article.title}}</h2>
        <p class="text-secondary">&#128197;{{Article.created_at}} &#x1F464;{{Article.user}}</p>

        {% if Article.image %}
          <img src="{{ Article.image.url}}" width="600" height="400" alt="{{Article.image}}">
        {% endif %}   

        <p>{{Article.content}}</p>
       
        {% for tag in mytag %}
            {% if tag.id == Article.id %} 
                  <div class="btn btn-secondary btn-sm">{{tag.tag__tags}} </div>  
            {% endif%}
        {% endfor %}
        <hr>
      {% endfor %} 
    </div>

    <div class="col-md-3">
        <h2 class="text-success">Popular Tags:</h2>
        {% for tag in tags %}
        <div class=" btn btn-secondary btn-sm">{{tag.tag__tags}}</div>
        {% endfor %} 
     </div>
     
     
  </div>
</div>
{% endblock content %}

articleApp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    .center {
      margin: 25px auto;
      width: 60%;
      padding: 10px;
      box-shadow: 1px 0px 5px 0px;
      
    }
    </style>
    <style>
      .centerform {
        margin: 25px auto;
        width: 30%;
        padding: 20px;
        box-shadow: 1px 0px 9px 1px;
      }
      .navbar3d{
        box-shadow: 1px 0px 9px 1px;
      }
      </style>
</head>
<body>
  <nav class="navbar sticky-top alert-primary navbar3d">
    <div class="container-fluid" >
      <a class="navbar-brand" href="#">Intellial Solution</a>
      <div class="d-grid gap-2 col-6 mx-auto">
        <a type="button" href="{% url 'articleApp:articleList' %}" class="btn btn-outline-dark">Article</a>
      </div>
    
      {% if user.is_authenticated %}
      <div>
        <a type="button" href="{% url 'articleApp:myarticle' %}" class="btn btn-outline-dark">My Artical</a>
        <a type="button" href="{% url 'articleApp:draft' %}" class="btn btn-outline-dark">Draft</a>
        <a type="button" href="{% url 'articleApp:article' %}" class="btn btn-outline-dark">Add Article</a>
        <a type="button" href="{% url 'articleApp:logout' %}" class="btn btn-outline-danger">Logout</a>
        <a class="btn btn-success">&#x1F464; {{request.user}}</a>
      </div>
      {% else %}
      <div>
      
        <a type="button" href="{% url 'articleApp:login' %}" class="btn btn-outline-dark">Login</a>
        <a type="button" href="{% url 'articleApp:signup' %}" class="btn btn-outline-dark">Signup</a>
     </div>
      {% endif %}
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

articleApp/templates/draftList.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
  <div>
    {% for Article in draftList %}
    <div class="center">
        <h2 class="text-primary">{{Article.title}}</h2>
        <p class="text-secondary">&#128197;{{Article.created_at}} &#x1F464;{{Article.user}}</p>
        {% if Article.image %}
          <img src="{{ Article.image.url}}" width="600" height="400" alt="{{Article.image}}">
        {% endif %}   
        <p>{{Article.content}}</p>

        {% for tag in mytag %}
            {% if tag.id == Article.id %} 
                  <div class="btn btn-secondary btn-sm">{{tag.tag__tags}} </div>  
            {% endif%}
        {% endfor %}
        <br><br>
        <a type="button" href="{% url 'articleApp:delete' Article.id %}" class="btn btn-danger btn-sm">Delete</a>
        <a type="button" href="{% url 'articleApp:update' Article.id %}" class="btn btn-warning btn-sm">Update</a>
         
      </div>
    {% endfor %} 
  </div>
{% endblock content %}

articleApp/templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container-fluid center">

  <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <h2>Intellial Solution</h2>
      <label  class="form-label">login Form</label>
      {{form.as_p}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>


  </form>
  </div>
  {% endblock content %}

articleApp/templates/myarticle.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
  <div>
    {% for Article in myarticle %}
    <div class="center">
      <h2 class="text-primary">{{Article.title}}</h2>
      <p class="text-secondary">&#128197;{{Article.created_at}} &#x1F464;{{Article.user}}</p>

      {% if Article.image %}
        <img src="{{ Article.image.url}}" width="600" height="400" alt="{{Article.image}}">
      {% endif %}   

      <p>{{Article.content}}</p>
  

      {% for tag in mytag %}
            {% if tag.id == Article.id %} 
                   <div class="btn btn-secondary btn-sm">{{tag.tag__tags}} </div>  
             {% endif%}
      {% endfor %}
    
      <br><br>

      <a type="button" href="{% url 'articleApp:delete' Article.id %}" class="btn btn-danger btn-sm">Delete</a>
      <a type="button" href="{% url 'articleApp:update' Article.id %}" class="btn btn-warning btn-sm">Update</a>

    
    </div>
    {% endfor %} 
    
  </div>
{% endblock content %}

articleApp/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid center">
  <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <h2>Intellial Solution</h2>
      <label  class="form-label">Registration Form</label>
      {{form.as_p}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  </div>
{% endblock content %}

articleApp/templates/updatearticle.html
{% extends 'base.html' %}

{% block content %}
  <div class="centerform">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <div class="mb-3">
        <label  class="form-label">Title</label>
        <p>{{form.title}}</p>
      </div>
      <div class="mb-3">
        <label  class="form-label">Content</label>
        <p>{{form.content}}</p>
      </div>
      <div class="mb-3">
        <label  class="form-label">Image</label>
       <p> {{form.image}}</p>
      </div>
      <div class="mb-3">
        <label class="form-label">Tags</label>
        <p>{{form2.articletag}}</p>
      </div>
      <div class="mb-3">
        <p>{{form.draft}} Save As Draft</p>
      </div>
      <button type="submit" class="btn btn-success">Save</button>
      <a type="button" href="{% url 'articleApp:myarticle' %}" class="btn btn-danger">Cancel</a>

    </div>
  </form>
  
  </div>

  {% endblock content %}